### ISSUE TITLE
css-modules/composed-class-names breaks if classname contains 'from'

### ISSUE THREAD

**Issue by monodop** [juanca/stylelint-css-modules#40]
I was experimenting with this linter a little bit and noticed that the `from` check catches some stuff it probably shouldn't.

Example:

```css
.from-class {
    text-align: right;
}

.composes-class {
    composes: from-class;
}
```

results in a linter error:
```
Unable to find file "/home/monodop/stylelint-test/clas"             css-modules/composed-class-names
```

I haven't tested, but I do wonder if it would also break if the url contained `from` as well.
